version: "3"
services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: php Solver.php
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=application
